name: ECG-Signal-Anomaly-Detection-Model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - pip=23.2.1
  - pip:
    - tensorflow==2.13.0
    - Werkzeug==2.0.1
    - Jinja2==3.1.4
    - MarkupSafe==2.1.3
    - itsdangerous==2.0.1
